# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-27 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=6)),
                ('id_number', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('telephone', models.CharField(max_length=11)),
                ('region', models.CharField(max_length=16)),
                ('education', models.CharField(blank=True, max_length=3, null=True)),
                ('school', models.CharField(blank=True, max_length=128, null=True)),
                ('graduatet_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'all_message',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'password',
            },
        ),
        migrations.CreateModel(
            name='FangInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoqu', models.CharField(max_length=32, verbose_name='小区')),
                ('danyuan', models.CharField(max_length=16, verbose_name='单元')),
                ('fjnumber', models.CharField(max_length=4, verbose_name='房间号')),
                ('chaoxiang', models.IntegerField(choices=[(1, '东'), (2, '南'), (3, '西'), (4, '北'), (5, '南北')])),
                ('mianji', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='面积')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('put_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.AllMessage', verbose_name='录入人')),
            ],
            options={
                'db_table': 'new_fang',
            },
        ),
    ]
