# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-27 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanginfo',
            name='louhao',
            field=models.IntegerField(default=1, verbose_name='楼号'),
        ),
        migrations.AlterField(
            model_name='fanginfo',
            name='danyuan',
            field=models.IntegerField(verbose_name='单元'),
        ),
        migrations.AlterField(
            model_name='fanginfo',
            name='fjnumber',
            field=models.IntegerField(verbose_name='房间号'),
        ),
    ]
